server:
  port: 8100

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://39.104.165.155:3306/management?characterEncoding=UTF-8&useUnicode=true&&useSSL=true&characterSetResults=utf8  #jdbc:mysql://39.104.165.155 172.24.32.169 localhost:3306/dbgirl_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    url: jdbc:mysql://10.112.12.81:3306/BUPT_IOT?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    cachePrepStmts: true  # 开启二级缓存

mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
  type-aliases-package: org.spring.springboot.domain
