// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Device.proto

package cn.edu.bupt.demo.protobuf;

public final class DeviceProto {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Device_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Device_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014Device.proto\"\360\001\n\006Device\022\n\n\002id\030\001 \001(\t\022\020\n" +
                        "\010tenantId\030\002 \001(\005\022\022\n\ncustomerId\030\003 \001(\005\022\014\n\004n" +
                        "ame\030\004 \001(\t\022\022\n\nsearchText\030\005 \001(\t\022\026\n\016parentD" +
                        "eviceId\030\006 \001(\t\022\022\n\ndeviceType\030\007 \001(\t\022\023\n\013man" +
                        "ufacture\030\010 \001(\t\022\r\n\005model\030\t \001(\t\022\016\n\006status\030" +
                        "\n \001(\t\022\020\n\010location\030\013 \001(\t\022\016\n\006siteId\030\014 \001(\t\022" +
                        "\020\n\010lifeTime\030\r \001(\003B+\n\031cn.edu.bupt.demo.pr" +
                        "otobufB\013DeviceProto\210\001\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Device_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Device_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Device_descriptor,
                new java.lang.String[]{"Id", "TenantId", "CustomerId", "Name", "SearchText", "ParentDeviceId", "DeviceType", "Manufacture", "Model", "Status", "Location", "SiteId", "LifeTime",});
    }

    private DeviceProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface DeviceOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Device)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string id = 1;</code>
         *
         * @return The id.
         */
        java.lang.String getId();

        /**
         * <code>string id = 1;</code>
         *
         * @return The bytes for id.
         */
        com.google.protobuf.ByteString
        getIdBytes();

        /**
         * <code>int32 tenantId = 2;</code>
         *
         * @return The tenantId.
         */
        int getTenantId();

        /**
         * <code>int32 customerId = 3;</code>
         *
         * @return The customerId.
         */
        int getCustomerId();

        /**
         * <code>string name = 4;</code>
         *
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <code>string name = 4;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>string searchText = 5;</code>
         *
         * @return The searchText.
         */
        java.lang.String getSearchText();

        /**
         * <code>string searchText = 5;</code>
         *
         * @return The bytes for searchText.
         */
        com.google.protobuf.ByteString
        getSearchTextBytes();

        /**
         * <code>string parentDeviceId = 6;</code>
         *
         * @return The parentDeviceId.
         */
        java.lang.String getParentDeviceId();

        /**
         * <code>string parentDeviceId = 6;</code>
         *
         * @return The bytes for parentDeviceId.
         */
        com.google.protobuf.ByteString
        getParentDeviceIdBytes();

        /**
         * <code>string deviceType = 7;</code>
         *
         * @return The deviceType.
         */
        java.lang.String getDeviceType();

        /**
         * <code>string deviceType = 7;</code>
         *
         * @return The bytes for deviceType.
         */
        com.google.protobuf.ByteString
        getDeviceTypeBytes();

        /**
         * <code>string manufacture = 8;</code>
         *
         * @return The manufacture.
         */
        java.lang.String getManufacture();

        /**
         * <code>string manufacture = 8;</code>
         *
         * @return The bytes for manufacture.
         */
        com.google.protobuf.ByteString
        getManufactureBytes();

        /**
         * <code>string model = 9;</code>
         *
         * @return The model.
         */
        java.lang.String getModel();

        /**
         * <code>string model = 9;</code>
         *
         * @return The bytes for model.
         */
        com.google.protobuf.ByteString
        getModelBytes();

        /**
         * <code>string status = 10;</code>
         *
         * @return The status.
         */
        java.lang.String getStatus();

        /**
         * <code>string status = 10;</code>
         *
         * @return The bytes for status.
         */
        com.google.protobuf.ByteString
        getStatusBytes();

        /**
         * <code>string location = 11;</code>
         *
         * @return The location.
         */
        java.lang.String getLocation();

        /**
         * <code>string location = 11;</code>
         *
         * @return The bytes for location.
         */
        com.google.protobuf.ByteString
        getLocationBytes();

        /**
         * <code>string siteId = 12;</code>
         *
         * @return The siteId.
         */
        java.lang.String getSiteId();

        /**
         * <code>string siteId = 12;</code>
         *
         * @return The bytes for siteId.
         */
        com.google.protobuf.ByteString
        getSiteIdBytes();

        /**
         * <code>int64 lifeTime = 13;</code>
         *
         * @return The lifeTime.
         */
        long getLifeTime();
    }

    /**
     * Protobuf type {@code Device}
     */
    public static final class Device extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Device)
            DeviceOrBuilder {
        public static final int ID_FIELD_NUMBER = 1;
        public static final int TENANTID_FIELD_NUMBER = 2;
        public static final int CUSTOMERID_FIELD_NUMBER = 3;
        public static final int NAME_FIELD_NUMBER = 4;
        public static final int SEARCHTEXT_FIELD_NUMBER = 5;
        public static final int PARENTDEVICEID_FIELD_NUMBER = 6;
        public static final int DEVICETYPE_FIELD_NUMBER = 7;
        public static final int MANUFACTURE_FIELD_NUMBER = 8;
        public static final int MODEL_FIELD_NUMBER = 9;
        public static final int STATUS_FIELD_NUMBER = 10;
        public static final int LOCATION_FIELD_NUMBER = 11;
        public static final int SITEID_FIELD_NUMBER = 12;
        public static final int LIFETIME_FIELD_NUMBER = 13;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Device)
        private static final cn.edu.bupt.demo.protobuf.DeviceProto.Device DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Device>
                PARSER = new com.google.protobuf.AbstractParser<Device>() {
            @java.lang.Override
            public Device parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Device(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new cn.edu.bupt.demo.protobuf.DeviceProto.Device();
        }

        private volatile java.lang.Object id_;
        private int tenantId_;
        private int customerId_;
        private volatile java.lang.Object name_;
        private volatile java.lang.Object searchText_;
        private volatile java.lang.Object parentDeviceId_;
        private volatile java.lang.Object deviceType_;
        private volatile java.lang.Object manufacture_;
        private volatile java.lang.Object model_;
        private volatile java.lang.Object status_;
        private volatile java.lang.Object location_;
        private volatile java.lang.Object siteId_;
        private long lifeTime_;
        private byte memoizedIsInitialized = -1;
        // Use Device.newBuilder() to construct.
        private Device(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Device() {
            id_ = "";
            name_ = "";
            searchText_ = "";
            parentDeviceId_ = "";
            deviceType_ = "";
            manufacture_ = "";
            model_ = "";
            status_ = "";
            location_ = "";
            siteId_ = "";
        }

        private Device(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            id_ = s;
                            break;
                        }
                        case 16: {

                            tenantId_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            customerId_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            searchText_ = s;
                            break;
                        }
                        case 50: {
                            java.lang.String s = input.readStringRequireUtf8();

                            parentDeviceId_ = s;
                            break;
                        }
                        case 58: {
                            java.lang.String s = input.readStringRequireUtf8();

                            deviceType_ = s;
                            break;
                        }
                        case 66: {
                            java.lang.String s = input.readStringRequireUtf8();

                            manufacture_ = s;
                            break;
                        }
                        case 74: {
                            java.lang.String s = input.readStringRequireUtf8();

                            model_ = s;
                            break;
                        }
                        case 82: {
                            java.lang.String s = input.readStringRequireUtf8();

                            status_ = s;
                            break;
                        }
                        case 90: {
                            java.lang.String s = input.readStringRequireUtf8();

                            location_ = s;
                            break;
                        }
                        case 98: {
                            java.lang.String s = input.readStringRequireUtf8();

                            siteId_ = s;
                            break;
                        }
                        case 104: {

                            lifeTime_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.edu.bupt.demo.protobuf.DeviceProto.internal_static_Device_descriptor;
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(cn.edu.bupt.demo.protobuf.DeviceProto.Device prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static cn.edu.bupt.demo.protobuf.DeviceProto.Device getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Device> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Device();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.edu.bupt.demo.protobuf.DeviceProto.internal_static_Device_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.edu.bupt.demo.protobuf.DeviceProto.Device.class, cn.edu.bupt.demo.protobuf.DeviceProto.Device.Builder.class);
        }

        /**
         * <code>string id = 1;</code>
         *
         * @return The id.
         */
        public java.lang.String getId() {
            java.lang.Object ref = id_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                id_ = s;
                return s;
            }
        }

        /**
         * <code>string id = 1;</code>
         *
         * @return The bytes for id.
         */
        public com.google.protobuf.ByteString
        getIdBytes() {
            java.lang.Object ref = id_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>int32 tenantId = 2;</code>
         *
         * @return The tenantId.
         */
        public int getTenantId() {
            return tenantId_;
        }

        /**
         * <code>int32 customerId = 3;</code>
         *
         * @return The customerId.
         */
        public int getCustomerId() {
            return customerId_;
        }

        /**
         * <code>string name = 4;</code>
         *
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 4;</code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string searchText = 5;</code>
         *
         * @return The searchText.
         */
        public java.lang.String getSearchText() {
            java.lang.Object ref = searchText_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                searchText_ = s;
                return s;
            }
        }

        /**
         * <code>string searchText = 5;</code>
         *
         * @return The bytes for searchText.
         */
        public com.google.protobuf.ByteString
        getSearchTextBytes() {
            java.lang.Object ref = searchText_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                searchText_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string parentDeviceId = 6;</code>
         *
         * @return The parentDeviceId.
         */
        public java.lang.String getParentDeviceId() {
            java.lang.Object ref = parentDeviceId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                parentDeviceId_ = s;
                return s;
            }
        }

        /**
         * <code>string parentDeviceId = 6;</code>
         *
         * @return The bytes for parentDeviceId.
         */
        public com.google.protobuf.ByteString
        getParentDeviceIdBytes() {
            java.lang.Object ref = parentDeviceId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                parentDeviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string deviceType = 7;</code>
         *
         * @return The deviceType.
         */
        public java.lang.String getDeviceType() {
            java.lang.Object ref = deviceType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deviceType_ = s;
                return s;
            }
        }

        /**
         * <code>string deviceType = 7;</code>
         *
         * @return The bytes for deviceType.
         */
        public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
            java.lang.Object ref = deviceType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deviceType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string manufacture = 8;</code>
         *
         * @return The manufacture.
         */
        public java.lang.String getManufacture() {
            java.lang.Object ref = manufacture_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                manufacture_ = s;
                return s;
            }
        }

        /**
         * <code>string manufacture = 8;</code>
         *
         * @return The bytes for manufacture.
         */
        public com.google.protobuf.ByteString
        getManufactureBytes() {
            java.lang.Object ref = manufacture_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                manufacture_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string model = 9;</code>
         *
         * @return The model.
         */
        public java.lang.String getModel() {
            java.lang.Object ref = model_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                model_ = s;
                return s;
            }
        }

        /**
         * <code>string model = 9;</code>
         *
         * @return The bytes for model.
         */
        public com.google.protobuf.ByteString
        getModelBytes() {
            java.lang.Object ref = model_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                model_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string status = 10;</code>
         *
         * @return The status.
         */
        public java.lang.String getStatus() {
            java.lang.Object ref = status_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                status_ = s;
                return s;
            }
        }

        /**
         * <code>string status = 10;</code>
         *
         * @return The bytes for status.
         */
        public com.google.protobuf.ByteString
        getStatusBytes() {
            java.lang.Object ref = status_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                status_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string location = 11;</code>
         *
         * @return The location.
         */
        public java.lang.String getLocation() {
            java.lang.Object ref = location_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                location_ = s;
                return s;
            }
        }

        /**
         * <code>string location = 11;</code>
         *
         * @return The bytes for location.
         */
        public com.google.protobuf.ByteString
        getLocationBytes() {
            java.lang.Object ref = location_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                location_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string siteId = 12;</code>
         *
         * @return The siteId.
         */
        public java.lang.String getSiteId() {
            java.lang.Object ref = siteId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                siteId_ = s;
                return s;
            }
        }

        /**
         * <code>string siteId = 12;</code>
         *
         * @return The bytes for siteId.
         */
        public com.google.protobuf.ByteString
        getSiteIdBytes() {
            java.lang.Object ref = siteId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                siteId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>int64 lifeTime = 13;</code>
         *
         * @return The lifeTime.
         */
        public long getLifeTime() {
            return lifeTime_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
            }
            if (tenantId_ != 0) {
                output.writeInt32(2, tenantId_);
            }
            if (customerId_ != 0) {
                output.writeInt32(3, customerId_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
            }
            if (!getSearchTextBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, searchText_);
            }
            if (!getParentDeviceIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, parentDeviceId_);
            }
            if (!getDeviceTypeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, deviceType_);
            }
            if (!getManufactureBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, manufacture_);
            }
            if (!getModelBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 9, model_);
            }
            if (!getStatusBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 10, status_);
            }
            if (!getLocationBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 11, location_);
            }
            if (!getSiteIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 12, siteId_);
            }
            if (lifeTime_ != 0L) {
                output.writeInt64(13, lifeTime_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
            }
            if (tenantId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, tenantId_);
            }
            if (customerId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, customerId_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
            }
            if (!getSearchTextBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, searchText_);
            }
            if (!getParentDeviceIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, parentDeviceId_);
            }
            if (!getDeviceTypeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, deviceType_);
            }
            if (!getManufactureBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, manufacture_);
            }
            if (!getModelBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, model_);
            }
            if (!getStatusBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, status_);
            }
            if (!getLocationBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, location_);
            }
            if (!getSiteIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, siteId_);
            }
            if (lifeTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(13, lifeTime_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof cn.edu.bupt.demo.protobuf.DeviceProto.Device)) {
                return super.equals(obj);
            }
            cn.edu.bupt.demo.protobuf.DeviceProto.Device other = (cn.edu.bupt.demo.protobuf.DeviceProto.Device) obj;

            if (!getId()
                    .equals(other.getId())) return false;
            if (getTenantId()
                    != other.getTenantId()) return false;
            if (getCustomerId()
                    != other.getCustomerId()) return false;
            if (!getName()
                    .equals(other.getName())) return false;
            if (!getSearchText()
                    .equals(other.getSearchText())) return false;
            if (!getParentDeviceId()
                    .equals(other.getParentDeviceId())) return false;
            if (!getDeviceType()
                    .equals(other.getDeviceType())) return false;
            if (!getManufacture()
                    .equals(other.getManufacture())) return false;
            if (!getModel()
                    .equals(other.getModel())) return false;
            if (!getStatus()
                    .equals(other.getStatus())) return false;
            if (!getLocation()
                    .equals(other.getLocation())) return false;
            if (!getSiteId()
                    .equals(other.getSiteId())) return false;
            if (getLifeTime()
                    != other.getLifeTime()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId().hashCode();
            hash = (37 * hash) + TENANTID_FIELD_NUMBER;
            hash = (53 * hash) + getTenantId();
            hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
            hash = (53 * hash) + getCustomerId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + SEARCHTEXT_FIELD_NUMBER;
            hash = (53 * hash) + getSearchText().hashCode();
            hash = (37 * hash) + PARENTDEVICEID_FIELD_NUMBER;
            hash = (53 * hash) + getParentDeviceId().hashCode();
            hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
            hash = (53 * hash) + getDeviceType().hashCode();
            hash = (37 * hash) + MANUFACTURE_FIELD_NUMBER;
            hash = (53 * hash) + getManufacture().hashCode();
            hash = (37 * hash) + MODEL_FIELD_NUMBER;
            hash = (53 * hash) + getModel().hashCode();
            hash = (37 * hash) + STATUS_FIELD_NUMBER;
            hash = (53 * hash) + getStatus().hashCode();
            hash = (37 * hash) + LOCATION_FIELD_NUMBER;
            hash = (53 * hash) + getLocation().hashCode();
            hash = (37 * hash) + SITEID_FIELD_NUMBER;
            hash = (53 * hash) + getSiteId().hashCode();
            hash = (37 * hash) + LIFETIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getLifeTime());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Device> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public cn.edu.bupt.demo.protobuf.DeviceProto.Device getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code Device}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Device)
                cn.edu.bupt.demo.protobuf.DeviceProto.DeviceOrBuilder {
            private java.lang.Object id_ = "";
            private int tenantId_;
            private int customerId_;
            private java.lang.Object name_ = "";
            private java.lang.Object searchText_ = "";
            private java.lang.Object parentDeviceId_ = "";
            private java.lang.Object deviceType_ = "";
            private java.lang.Object manufacture_ = "";
            private java.lang.Object model_ = "";
            private java.lang.Object status_ = "";
            private java.lang.Object location_ = "";
            private java.lang.Object siteId_ = "";
            private long lifeTime_;

            // Construct using cn.edu.bupt.demo.protobuf.DeviceProto.Device.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return cn.edu.bupt.demo.protobuf.DeviceProto.internal_static_Device_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return cn.edu.bupt.demo.protobuf.DeviceProto.internal_static_Device_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                cn.edu.bupt.demo.protobuf.DeviceProto.Device.class, cn.edu.bupt.demo.protobuf.DeviceProto.Device.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = "";

                tenantId_ = 0;

                customerId_ = 0;

                name_ = "";

                searchText_ = "";

                parentDeviceId_ = "";

                deviceType_ = "";

                manufacture_ = "";

                model_ = "";

                status_ = "";

                location_ = "";

                siteId_ = "";

                lifeTime_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return cn.edu.bupt.demo.protobuf.DeviceProto.internal_static_Device_descriptor;
            }

            @java.lang.Override
            public cn.edu.bupt.demo.protobuf.DeviceProto.Device getDefaultInstanceForType() {
                return cn.edu.bupt.demo.protobuf.DeviceProto.Device.getDefaultInstance();
            }

            @java.lang.Override
            public cn.edu.bupt.demo.protobuf.DeviceProto.Device build() {
                cn.edu.bupt.demo.protobuf.DeviceProto.Device result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public cn.edu.bupt.demo.protobuf.DeviceProto.Device buildPartial() {
                cn.edu.bupt.demo.protobuf.DeviceProto.Device result = new cn.edu.bupt.demo.protobuf.DeviceProto.Device(this);
                result.id_ = id_;
                result.tenantId_ = tenantId_;
                result.customerId_ = customerId_;
                result.name_ = name_;
                result.searchText_ = searchText_;
                result.parentDeviceId_ = parentDeviceId_;
                result.deviceType_ = deviceType_;
                result.manufacture_ = manufacture_;
                result.model_ = model_;
                result.status_ = status_;
                result.location_ = location_;
                result.siteId_ = siteId_;
                result.lifeTime_ = lifeTime_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof cn.edu.bupt.demo.protobuf.DeviceProto.Device) {
                    return mergeFrom((cn.edu.bupt.demo.protobuf.DeviceProto.Device) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(cn.edu.bupt.demo.protobuf.DeviceProto.Device other) {
                if (other == cn.edu.bupt.demo.protobuf.DeviceProto.Device.getDefaultInstance()) return this;
                if (!other.getId().isEmpty()) {
                    id_ = other.id_;
                    onChanged();
                }
                if (other.getTenantId() != 0) {
                    setTenantId(other.getTenantId());
                }
                if (other.getCustomerId() != 0) {
                    setCustomerId(other.getCustomerId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getSearchText().isEmpty()) {
                    searchText_ = other.searchText_;
                    onChanged();
                }
                if (!other.getParentDeviceId().isEmpty()) {
                    parentDeviceId_ = other.parentDeviceId_;
                    onChanged();
                }
                if (!other.getDeviceType().isEmpty()) {
                    deviceType_ = other.deviceType_;
                    onChanged();
                }
                if (!other.getManufacture().isEmpty()) {
                    manufacture_ = other.manufacture_;
                    onChanged();
                }
                if (!other.getModel().isEmpty()) {
                    model_ = other.model_;
                    onChanged();
                }
                if (!other.getStatus().isEmpty()) {
                    status_ = other.status_;
                    onChanged();
                }
                if (!other.getLocation().isEmpty()) {
                    location_ = other.location_;
                    onChanged();
                }
                if (!other.getSiteId().isEmpty()) {
                    siteId_ = other.siteId_;
                    onChanged();
                }
                if (other.getLifeTime() != 0L) {
                    setLifeTime(other.getLifeTime());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                cn.edu.bupt.demo.protobuf.DeviceProto.Device parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (cn.edu.bupt.demo.protobuf.DeviceProto.Device) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string id = 1;</code>
             *
             * @return The id.
             */
            public java.lang.String getId() {
                java.lang.Object ref = id_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    id_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string id = 1;</code>
             *
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string id = 1;</code>
             *
             * @return The bytes for id.
             */
            public com.google.protobuf.ByteString
            getIdBytes() {
                java.lang.Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string id = 1;</code>
             *
             * @param value The bytes for id to set.
             * @return This builder for chaining.
             */
            public Builder setIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string id = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearId() {

                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }

            /**
             * <code>int32 tenantId = 2;</code>
             *
             * @return The tenantId.
             */
            public int getTenantId() {
                return tenantId_;
            }

            /**
             * <code>int32 tenantId = 2;</code>
             *
             * @param value The tenantId to set.
             * @return This builder for chaining.
             */
            public Builder setTenantId(int value) {

                tenantId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 tenantId = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTenantId() {

                tenantId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>int32 customerId = 3;</code>
             *
             * @return The customerId.
             */
            public int getCustomerId() {
                return customerId_;
            }

            /**
             * <code>int32 customerId = 3;</code>
             *
             * @param value The customerId to set.
             * @return This builder for chaining.
             */
            public Builder setCustomerId(int value) {

                customerId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 customerId = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCustomerId() {

                customerId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 4;</code>
             *
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 4;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 4;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 4;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string searchText = 5;</code>
             *
             * @return The searchText.
             */
            public java.lang.String getSearchText() {
                java.lang.Object ref = searchText_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    searchText_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string searchText = 5;</code>
             *
             * @param value The searchText to set.
             * @return This builder for chaining.
             */
            public Builder setSearchText(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                searchText_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string searchText = 5;</code>
             *
             * @return The bytes for searchText.
             */
            public com.google.protobuf.ByteString
            getSearchTextBytes() {
                java.lang.Object ref = searchText_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    searchText_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string searchText = 5;</code>
             *
             * @param value The bytes for searchText to set.
             * @return This builder for chaining.
             */
            public Builder setSearchTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                searchText_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string searchText = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSearchText() {

                searchText_ = getDefaultInstance().getSearchText();
                onChanged();
                return this;
            }

            /**
             * <code>string parentDeviceId = 6;</code>
             *
             * @return The parentDeviceId.
             */
            public java.lang.String getParentDeviceId() {
                java.lang.Object ref = parentDeviceId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    parentDeviceId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string parentDeviceId = 6;</code>
             *
             * @param value The parentDeviceId to set.
             * @return This builder for chaining.
             */
            public Builder setParentDeviceId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                parentDeviceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string parentDeviceId = 6;</code>
             *
             * @return The bytes for parentDeviceId.
             */
            public com.google.protobuf.ByteString
            getParentDeviceIdBytes() {
                java.lang.Object ref = parentDeviceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    parentDeviceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string parentDeviceId = 6;</code>
             *
             * @param value The bytes for parentDeviceId to set.
             * @return This builder for chaining.
             */
            public Builder setParentDeviceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                parentDeviceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string parentDeviceId = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearParentDeviceId() {

                parentDeviceId_ = getDefaultInstance().getParentDeviceId();
                onChanged();
                return this;
            }

            /**
             * <code>string deviceType = 7;</code>
             *
             * @return The deviceType.
             */
            public java.lang.String getDeviceType() {
                java.lang.Object ref = deviceType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    deviceType_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string deviceType = 7;</code>
             *
             * @param value The deviceType to set.
             * @return This builder for chaining.
             */
            public Builder setDeviceType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                deviceType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string deviceType = 7;</code>
             *
             * @return The bytes for deviceType.
             */
            public com.google.protobuf.ByteString
            getDeviceTypeBytes() {
                java.lang.Object ref = deviceType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    deviceType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string deviceType = 7;</code>
             *
             * @param value The bytes for deviceType to set.
             * @return This builder for chaining.
             */
            public Builder setDeviceTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                deviceType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string deviceType = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDeviceType() {

                deviceType_ = getDefaultInstance().getDeviceType();
                onChanged();
                return this;
            }

            /**
             * <code>string manufacture = 8;</code>
             *
             * @return The manufacture.
             */
            public java.lang.String getManufacture() {
                java.lang.Object ref = manufacture_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    manufacture_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string manufacture = 8;</code>
             *
             * @param value The manufacture to set.
             * @return This builder for chaining.
             */
            public Builder setManufacture(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                manufacture_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string manufacture = 8;</code>
             *
             * @return The bytes for manufacture.
             */
            public com.google.protobuf.ByteString
            getManufactureBytes() {
                java.lang.Object ref = manufacture_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    manufacture_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string manufacture = 8;</code>
             *
             * @param value The bytes for manufacture to set.
             * @return This builder for chaining.
             */
            public Builder setManufactureBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                manufacture_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string manufacture = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearManufacture() {

                manufacture_ = getDefaultInstance().getManufacture();
                onChanged();
                return this;
            }

            /**
             * <code>string model = 9;</code>
             *
             * @return The model.
             */
            public java.lang.String getModel() {
                java.lang.Object ref = model_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    model_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string model = 9;</code>
             *
             * @param value The model to set.
             * @return This builder for chaining.
             */
            public Builder setModel(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                model_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string model = 9;</code>
             *
             * @return The bytes for model.
             */
            public com.google.protobuf.ByteString
            getModelBytes() {
                java.lang.Object ref = model_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    model_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string model = 9;</code>
             *
             * @param value The bytes for model to set.
             * @return This builder for chaining.
             */
            public Builder setModelBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                model_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string model = 9;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModel() {

                model_ = getDefaultInstance().getModel();
                onChanged();
                return this;
            }

            /**
             * <code>string status = 10;</code>
             *
             * @return The status.
             */
            public java.lang.String getStatus() {
                java.lang.Object ref = status_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    status_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string status = 10;</code>
             *
             * @param value The status to set.
             * @return This builder for chaining.
             */
            public Builder setStatus(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string status = 10;</code>
             *
             * @return The bytes for status.
             */
            public com.google.protobuf.ByteString
            getStatusBytes() {
                java.lang.Object ref = status_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    status_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string status = 10;</code>
             *
             * @param value The bytes for status to set.
             * @return This builder for chaining.
             */
            public Builder setStatusBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string status = 10;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearStatus() {

                status_ = getDefaultInstance().getStatus();
                onChanged();
                return this;
            }

            /**
             * <code>string location = 11;</code>
             *
             * @return The location.
             */
            public java.lang.String getLocation() {
                java.lang.Object ref = location_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    location_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string location = 11;</code>
             *
             * @param value The location to set.
             * @return This builder for chaining.
             */
            public Builder setLocation(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                location_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string location = 11;</code>
             *
             * @return The bytes for location.
             */
            public com.google.protobuf.ByteString
            getLocationBytes() {
                java.lang.Object ref = location_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    location_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string location = 11;</code>
             *
             * @param value The bytes for location to set.
             * @return This builder for chaining.
             */
            public Builder setLocationBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                location_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string location = 11;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLocation() {

                location_ = getDefaultInstance().getLocation();
                onChanged();
                return this;
            }

            /**
             * <code>string siteId = 12;</code>
             *
             * @return The siteId.
             */
            public java.lang.String getSiteId() {
                java.lang.Object ref = siteId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    siteId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string siteId = 12;</code>
             *
             * @param value The siteId to set.
             * @return This builder for chaining.
             */
            public Builder setSiteId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                siteId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string siteId = 12;</code>
             *
             * @return The bytes for siteId.
             */
            public com.google.protobuf.ByteString
            getSiteIdBytes() {
                java.lang.Object ref = siteId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    siteId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string siteId = 12;</code>
             *
             * @param value The bytes for siteId to set.
             * @return This builder for chaining.
             */
            public Builder setSiteIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                siteId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string siteId = 12;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSiteId() {

                siteId_ = getDefaultInstance().getSiteId();
                onChanged();
                return this;
            }

            /**
             * <code>int64 lifeTime = 13;</code>
             *
             * @return The lifeTime.
             */
            public long getLifeTime() {
                return lifeTime_;
            }

            /**
             * <code>int64 lifeTime = 13;</code>
             *
             * @param value The lifeTime to set.
             * @return This builder for chaining.
             */
            public Builder setLifeTime(long value) {

                lifeTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 lifeTime = 13;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLifeTime() {

                lifeTime_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Device)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
